services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    restart: unless-stopped

  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - inception
    restart: unless-stopped

networks:
  inception:
    driver: bridge